name: Generate snake animation

on:
  schedule: # execute every 24 hours
    - cron: "0 0 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: generate snake-dark.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: SudoKMaar
          outputs: dist/github-snake-dark.svg?palette=github-dark&color_snake=#FFB000

      - name: generate snake-light.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: SudoKMaar
          outputs: dist/github-snake.svg?palette=github-light&color_snake=#7957D5

      - name: push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
